server:
  port: 8899
spring:
  flyway:
    baseline-on-migrate: true
  application:
    name: hotpot-service
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://122.51.99.64:3306/hotpot_gz?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: zhoukaile
    driver-class-name: com.mysql.cj.jdbc.Driver
  #设置驼峰命名法
mybatis:
  configuration:
    map-underscore-to-camel-case: true

wx:
  mp:
    configs:
      - appId: wx839d5e2b8c199be6
        secret: 5192795b44417d1e96c2b16184979e5c
        token: zxcasdqwe123
        aesKey: utf-8
