server:
  port: 8899
spring:
  flyway:
    baseline-on-migrate: true
  application:
    name: hotpot-service
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  mvc:
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://localhost:3306/hotpot_gz?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #设置驼峰命名法
mybatis:
  configuration:
    map-underscore-to-camel-case: true
wx:
  mp:
    configs:
      - appId: wx7a269cd5c959d0fd
        secret: 3a9557fb46f1981f01927f8cf7389719
        token: zklzzzz123
        aesKey: utf-8





